from django.urls import path
from .views import (
    CreatePrivateChatView,
    CreateGroupChatView,
    UserChatRoomsView,
    RoomMessagesView,
    SendMessageView,
    EditMessageView,
    DeleteMessageView,
    TranslateBatchView,
    ForwardMessageView,
    # DeleteGroupView,
    DeleteRoomView,
    AddGroupMemberView,
    GroupMembersView,
    PromoteAdminView,
    ExitGroupView,
    RemoveGroupMemberView,
    ForwardMultipleMessagesView,
    SearchMessagesView,
    PinMessageView,
    UnpinMessageView, 
    GiphySearchView, 
    StickerPackListView, 
    StickerView
)

urlpatterns = [
    path("private/", CreatePrivateChatView.as_view()),
    path("group/", CreateGroupChatView.as_view()),
    path("rooms/", UserChatRoomsView.as_view()),
    path("rooms/<int:room_id>/messages/", RoomMessagesView.as_view()),
    path("rooms/<int:room_id>/send/", SendMessageView.as_view()),
    path("messages/edit/", EditMessageView.as_view()),
    path("messages/delete/", DeleteMessageView.as_view()),
    path("translate-batch/", TranslateBatchView.as_view()),
    path('forward/', ForwardMessageView.as_view()),
    path('rooms/<int:pk>/delete/', DeleteRoomView.as_view(), name='delete-room'),
    path('rooms/<int:room_id>/members/', GroupMembersView.as_view()),
    path('rooms/<int:room_id>/add_member/', AddGroupMemberView.as_view()),
    path('rooms/<int:room_id>/remove_member/', RemoveGroupMemberView.as_view()),
    path('rooms/<int:room_id>/promote_admin/', PromoteAdminView.as_view()),
    path('rooms/<int:room_id>/exit/', ExitGroupView.as_view()),
    path('forward-multiple/', ForwardMultipleMessagesView.as_view()),
    path("rooms/<int:room_id>/search/", SearchMessagesView.as_view()),
    path("rooms/<int:room_id>/pin/<int:message_id>/", PinMessageView.as_view()),
    path("rooms/<int:room_id>/unpin/<int:message_id>/", UnpinMessageView.as_view()),
    path("giphy/search/", GiphySearchView.as_view()),
    path("stickers/", StickerPackListView.as_view()),
    path("stickers/<int:pk>/", StickerView.as_view()),
]

