# Generated by Django 5.2.11 on 2026-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada')], default='en', max_length=2),
        ),
    ]
